name: Daily Builds test

on:
  workflow_call:
    inputs:
      builds:
        required: true
        type: string

jobs:
  daily_test:
    if: inputs.builds != '[]'
    strategy:
      fail-fast: false
      matrix:
        build: ${{ fromJson(inputs.builds) }}
    uses: ./.github/workflows/release-build.yml
    name: Building ${{ matrix.build.v }}
    secrets: inherit
    with:
      version: ${{ matrix.build.v }}

  skip_dailt_test:
    if: inputs.builds == '[]'
    runs-on: [ubuntu-slim]
    steps:
      - name: No builds to do
        run: echo "No builds to do"
